=== kamal-F/Q2B20171A/barang.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="logbarang">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="barang"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="barang">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="kode"/>
                <xs:element name="satuan">
                	<xs:simpleType>
                		<xs:restriction base="xs:NCName">
                			<xs:minLength value="1"></xs:minLength>
                			<xs:pattern value="kg|pc|liter"></xs:pattern>
                		</xs:restriction>
                	</xs:simpleType>
                </xs:element>
                <xs:element ref="harga"/>
                <xs:element ref="asal"/>
                <xs:element ref="tujuan"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="kode" type="xs:NCName"/>
    <xs:element name="satuan">
    	<xs:simpleType>
    		<xs:restriction base="xs:NCName">
    			<xs:pattern value="kg"></xs:pattern>
    			<xs:pattern value="liter"></xs:pattern>
    			<xs:pattern value="pc"></xs:pattern>
    		</xs:restriction>
    	</xs:simpleType>
    </xs:element>
    <xs:element name="harga" type="xs:integer"/>
    <xs:element name="asal">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="pt"/>
                <xs:element ref="kodewil"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="tujuan">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="pt"/>
                <xs:element ref="kodewil"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="pt" type="xs:string"/>
    <xs:element name="kodewil" type="xs:integer"/>
</xs:schema>

=== kamal-F/Q2B20171A/barang.xml
<?xml version="1.0" encoding="UTF-8"?>
<logbarang xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="barang.xsd">
<barang>
	<kode>M11122</kode>
	<satuan>rupiah</satuan>
	<harga>5000</harga>
	<asal>
		<pt>ladyrock</pt>
		<kodewil>10</kodewil>
	</asal>
	<tujuan>
		<pt>union</pt>
		<kodewil>1001</kodewil>
	</tujuan>
</barang>
<barang>
	<kode>M1122</kode>
	<satuan>pc</satuan>
	<harga>1000</harga>
	<asal>
		<pt>pbm</pt>
		<kodewil>103</kodewil>
	</asal>
	<tujuan>
		<pt>mitra kencana</pt>
		<kodewil>300</kodewil>
	</tujuan>
</barang>
</logbarang>
